### PR TITLE
Modified test in order to show issue with namespaces

### PR DESCRIPTION
**Pull request by diorcety**

### CODE REVIEW

**Comment by diorcety** [comment]
This issue was introduced in 1.4 .. i didn't have this issue with 1.3

**Comment by diorcety** [comment]
it takes the wrong namespace. In my application it takes my base namespace instead of ""

**Comment by dmak** [comment]
Do I understand correctly that if you put container into container into container (all having different namespaces), the problem occurs?

**Comment by diorcety** [comment]
There are issues with namespace stuff.
The issue trigger by this test is different from my case.
I found the issue
if i generate to xsd with different namespace into the same package, the plugin uses ObjectFactory so there is an issue with namespace (get from ObjectFactory).
This test uses a xsd which an type extends a type from another xsd, the plugin put the the wrong namespace in the annotation

**Comment by dmak** [comment]
After I have applied your changes to the schema, the sample XML file `different-namespaces.xml` is not valid anymore. It requires that `<tests>` in XML is changed to `<tests xmlns="">`. Do you happen to know why? Perhaps that is written somewhere in XSD spec…
And then: namespace for what particular XML element is wrong? After I have corrected `different-namespaces.xml`, it is serialized and deserialized OK, that means that generated Java model corresponds to XSD.

**Comment by diorcety** [comment]
Yes but why change xmlns of tests by ""? it should be remain in http://example.com/container so no namespace override.

**Comment by dmak** [comment]
I cannot tell this as well, please ask somewhere else. From JAXB perspective, if XML validates against XSD, then Java model should parse and produce this XML. Do you have an example of valid XML document, which fails? If not, then you need to correct your XSD – Xew plugin can't help you here.

**Comment by dmak** [comment]
I have merged your changes with extra necessary fixes applied. I don't see where the problem exactly is. Could you tell me the element in XML (or Java model), for which namespace is wrong in your opinion?

**Comment by diorcety** [comment]
at the end none, i miss the elementFormDefault="qualified" in this example

**Comment by diorcety** [comment]
But i'm really confuse about that elementFormDefault:
http://stackoverflow.com/questions/1463138/what-does-elementformdefault-do-for-xml-when-is-it-used
http://www.xfront.com/HideVersusExpose.html
It seems that we sould not be forced to used elementFormDefault="qualified"

**Comment by dmak** [comment]
In [`different-namespaces.xml`](https://github.com/dmak/jaxb-xew-plugin/blob/master/src/test/resources/com/sun/tools/xjc/addon/xew/different-namespaces.xml) we don't need to specify namespace for `<tests>` because we have specified default namespace (`xmlns="http://example.com/namespaces"`) in its parent. However I cannot understand why after `<xs:extension>` was applied to `container` suddenly namepsace became "". I cannot unfortunately answer this question, this behaviour should be specified in [W3C document](http://www.w3.org/XML/Schema).

**Comment by diorcety** [comment]
I found how to reproduce... it must be a bug in jaxb.
1) Remove elementFormDefault="qualified" 
-> not working
2) Comment 
```
						<xs:element ref="entries:entries" minOccurs="0" />
						<xs:element ref="items:items" />
```
-> not working
3) Comment one or both of this import
```
	<xs:import schemaLocation="different-namespaces-entries.xsd" namespace="http://example.com/entries" />
	<xs:import schemaLocation="different-namespaces-items.xsd" namespace="http://example.com/items" />
```
--> it works

**Comment by diorcety** [comment]
Okay it must be 
```
<xs:import schemaLocation="different-namespaces-entry.xsd" namespace="http://example.com/entry" />
```
in different-namespaces-entries.xsd ***AND*** different-namespaces-items.xsd which cause issue to jaxb

**Comment by diorcety** [comment]
not the import itself but the usage of entry in each

**Comment by diorcety** [comment]
It comes from com.sun.tools.xjc.generator.bean.PackageOutlineImpl#getFormDefault and com.sun.tools.xjc.generator.bean.PackageOutlineImpl#getMostUsedURI

**Comment by dmak** [comment]
Again, sorry but I don't possess extrasensory abilities. I can't read your thoughts, so I have no clue what do you mean when you say "not working". If you could reproduce the problem without Xew plugin enabled, then you'd better post your question to stackoverflow and post the link here – I will certainly participate in discussion. Please provide your XSD and version of XJC you use to compile the model (or the model itself), and sample XML.

**Comment by diorcety** [comment]
Indeed :) sorry

**Comment by dmak** [comment]
I think that finally I have got the vision of the problem. Your issue relates to unqualified schema, as described in issue #40. Have a look there.

**Pull request merged**
